/*
 * File: app/store/MyJsonStore2.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.MyJsonStore2', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyJsonStore2',
            data: [
                [
                    'Alaska',
                    'active',
                    3.2
                ],
                [
                    'California',
                    'active',
                    0.4
                ],
                [
                    'Mexico',
                    'inactive',
                    5.9
                ],
                [
                    'California',
                    'inactive',
                    8.4
                ],
                [
                    'Mexico',
                    'inactive',
                    7.7
                ],
                [
                    'Mexico',
                    'inactive',
                    8.4
                ],
                [
                    'California',
                    'active',
                    5.6
                ],
                [
                    'Alaska',
                    'active',
                    8.1
                ],
                [
                    'California',
                    'active',
                    5.4
                ],
                [
                    'Alaska',
                    'inactive',
                    4.6
                ],
                [
                    'Mexico',
                    'inactive',
                    3.6
                ],
                [
                    'Alaska',
                    'inactive',
                    6.5
                ],
                [
                    'Alaska',
                    'inactive',
                    5.4
                ],
                [
                    'Mexico',
                    'active',
                    6.6
                ],
                [
                    'Mexico',
                    'active',
                    7.8
                ],
                [
                    'California',
                    'active',
                    4.5
                ],
                [
                    'Alaska',
                    'active',
                    6.6
                ],
                [
                    'Mexico',
                    'active',
                    7.4
                ],
                [
                    'Alaska',
                    'active',
                    7.7
                ],
                [
                    'California',
                    'active',
                    5.6
                ]
            ]
        }, cfg)]);
    }
});