/*
 * File: app/view/vwpMain.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.vwpMain', {
    extend: 'Ext.container.Viewport',

    id: 'vwpMain',
    autoScroll: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    cls: 'headerVec',
                    height: 110,
                    id: 'cntHeader',
                    layout: {
                        type: 'absolute'
                    },
                    items: [
                        {
                            xtype: 'image',
                            x: 0,
                            y: 0,
                            height: 110,
                            width: 130,
                            src: 'static/images/logoVerizon.jpg'
                        },
                        {
                            xtype: 'label',
                            x: 150,
                            y: 70,
                            cls: 'repairsTitle',
                            text: 'REPAIRS'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    id: 'cntAccess'
                },
                {
                    xtype: 'container',
                    activeItem: 1,
                    id: 'cntBody',
                    layout: {
                        type: 'card'
                    },
                    items: [
                        {
                            xtype: 'container',
                            id: 'cntTickets'
                        },
                        {
                            xtype: 'container',
                            id: 'cntTicketDetails',
                            items: [
                                {
                                    xtype: 'panel',
                                    cls: 'ticketDetailPanel',
                                    autoScroll: true,
                                    header: false,
                                    title: 'ticketDetail',
                                    items: [
                                        {
                                            xtype: 'dataview',
                                            tpl: [
                                                '<tpl for=".">',
                                                '    <tpl for="TicketDetail">',
                                                '        <div class="ticketNumber">Ticket {ticketNumber}</div>',
                                                '        <div class="htd">',
                                                '    ',
                                                '                <div class="htdSS">',
                                                '                    <div class="htdil">Service ID</div>',
                                                '                    <div class="htdi">{serviceID}</div>',
                                                '                </div>',
                                                '                <div class="htdPC">',
                                                '                    <div class="htdil">Primary Contact</div>',
                                                '                    <div class="htdi">{primaryContact}</div>',
                                                '                    <div class="htdi">|</div>',
                                                '                    <div class="htdi">{primaryContactPhone}</div>',
                                                '                </div>',
                                                '                <div class="htdSS">',
                                                '                    <div class="htdil">Status</div>',
                                                '                    <div class="htdis">{status}</div>',
                                                '                </div>',
                                                '        </div>',
                                                '	</tpl>',
                                                '    <div class="contenttable">',
                                                '		<div class="detailtTittle">Activity Log</div>',
                                                '        <table cellspacing="0" >',
                                                '            <tr>',
                                                '                <th class="thal-l">Log Date</th><th class="thal-m">Function Code</th><th class="thal-r">Description</th>',
                                                '            </tr>',
                                                '            <tpl for="ActivityLog">',
                                                '                <tr class="{[xindex % 2 === 0 ? "even-row":"odd-row"]}">',
                                                '                    <td class="tdal-l">{logDate}</td><td class="tdal-m">{functionCode}</td><td class="tdal-r last">{description}</td>',
                                                '                </tr>',
                                                '            </tpl>',
                                                '        </table>',
                                                '    </div>',
                                                '    ',
                                                '    <div class="contenttable">',
                                                '		<div class="detailtTittle">Ticket Log</div>',
                                                '        <table cellspacing="0">',
                                                '            <tr>',
                                                '                <th>Last Update Date/Time</th><th>Estimated Repair Time (HH:MM)</th><th>Elapsed Repair Time</th>',
                                                '            </tr>',
                                                '            <tpl for="TicketLog">',
                                                '                <tr>',
                                                '                    <td>{lastUpdated}</td><td>{estimatedRepairTime}</td><td>{elapsedRepairTime}</td>',
                                                '                </tr>',
                                                '            </tpl>',
                                                '        </table>',
                                                '    </div>',
                                                '    ',
                                                '</tpl>'
                                            ],
                                            store: 'ticketDetail'
                                        },
                                        {
                                            xtype: 'panel',
                                            cls: 'ticketDetailPanel',
                                            html: 'Ticket Log',
                                            bodyCls: [
                                                'acccls',
                                                'x-panel-body-default',
                                                'x-collapsed',
                                                'x-panel-body-collapsed',
                                                'x-panel-body-default-collapsed'
                                            ],
                                            collapsed: true,
                                            collapsible: true,
                                            title: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ticket Log',
                                            titleCollapse: true
                                        },
                                        {
                                            xtype: 'panel',
                                            cls: 'ticketDetailPanel',
                                            html: 'Service Information',
                                            bodyCls: [
                                                'acccls',
                                                'x-panel-body-default',
                                                'x-collapsed',
                                                'x-panel-body-collapsed',
                                                'x-panel-body-default-collapsed'
                                            ],
                                            collapsed: true,
                                            collapsible: true,
                                            title: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Service Information',
                                            titleCollapse: true
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});