/*
 * File: app/view/MyGridPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyGridPanel', {
    extend: 'Ext.grid.Panel',

    height: 250,
    width: 400,
    title: 'My Grid Panel',
    store: 'MyJsonStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    text: 'name'
                }
            ],
            plugins: [
                Ext.create('Ext.grid.plugin.BufferedRenderer', {
                    init: function() {
                        console.log("init plugin");

                    }
                })
            ]
        });

        me.callParent(arguments);
    }

});